name: tinc
version: '1.0.33'
summary: Virtual Private Network daemon creating a secure private network between hosts
description: |
  tinc is a Virtual Private Network (VPN) daemon that uses tunnelling and
  encryption to create a secure private network between hosts on the Internet.
  Because the VPN appears to the IP level network code as a normal network
  device, there is no need to adapt any existing software. This allows VPN sites
  to share information with each other over the Internet without exposing any
  information to others.

  Features:
  * Encryption, authentication and compression
  * Automatic full mesh routing
  * NAT traversal
  * Easily expand your VPN
  * Ability to bridge ethernet segments
  * Runs on many operating systems and supports IPv6

confinement: strict

apps:
  tinc:
    command: usr/sbin/tincd -c "$SNAP_DATA"
    plugs:
      - network
      - network-bind
      - network-control

  tincd:
    daemon: simple
    command: usr/sbin/tincd --no-detach --pidfile=$SNAP_COMMON/tinc.pid --chroot -c "$SNAP_DATA"
    plugs:
      - network
      - network-bind
      - network-control

parts:
  tinc:
    plugin: autotools
    source: git://tinc-vpn.org/tinc
    source-tag: release-1.0.33
    source-depth: 1
    configflags:
      - --prefix=/usr
    build-packages:
      - liblzo2-dev
      - libssl-dev
      - texinfo
      - zlib1g-dev
    stage-packages:
      - liblzo2-2
      - libssl1.0.0
      - zlib1g
